trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: BuildApp
  displayName: Build Apps
  jobs:
  - job: BuildFrontendApp
    displayName: Build Frontend App
    steps:
    - script: echo building frontend app
      displayName: build frontend app
    - script: echo running unit tests for frontend app
      displayName: unit tests frontend
    - script: echo deploying frontend app to DEV
      displayName: deploy frontend app to DEV
    - script: echo deploying frontend app to PROD
      displayName: deploy frontend app to PROD